apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app
  namespace: default
  labels:
    app: app
spec:
  storageClassName: efs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
